[package]
name = "index-macro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
tantivy = "0.22.0"
syn = { version = "2.0", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0"